# Generated by Django 2.1.5 on 2019-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infirmary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_department',
            name='hospital_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='beizhu1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='beizhu2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='beizhu3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='beizhu1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='beizhu2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='beizhu3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
