# Generated by Django 2.1.5 on 2019-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_appointment_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='seat_num',
            field=models.CharField(max_length=100),
        ),
    ]
