# Generated by Django 2.1.5 on 2019-03-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seats',
            name='seat_num',
            field=models.CharField(max_length=100),
        ),
    ]
